<a href="https://colab.research.google.com/github/sandeshchand/wineclassification/blob/main/wineclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analyse the information given in the following ‘Wines’ dataset and classify the wine based on their place of origin

In [ ]:
import pandas as pd
import numpy as np 
import sklearn as sk 
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.ensemble import RandomForestClassifier


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:

#import io 
#path="G:/Edurekatask/AI/Module3/wine.csv"

data=pd.read_csv(r"https://www.edureka.co/medias/giu1bur0kw/download?media_file_id=254929809")
data.head(5)

#data.value_counts()

Wine  Alcohol  Malic.acid   Ash  ...  Color.int   Hue    OD  Proline
0     1    14.23        1.71  2.43  ...       5.64  1.04  3.92     1065
1     1    13.20        1.78  2.14  ...       4.38  1.05  3.40     1050
2     1    13.16        2.36  2.67  ...       5.68  1.03  3.17     1185
3     1    14.37        1.95  2.50  ...       7.80  0.86  3.45     1480
4     1    13.24        2.59  2.87  ...       4.32  1.04  2.93      735

[5 rows x 14 columns]

In [ ]:
data.shape

(178, 14)

In [ ]:
data.isnull().sum()
data['Wine'].value_counts()

2    71
1    59
3    48
Name: Wine, dtype: int64

In [ ]:
X=data.iloc[:,1:]

print(X)

     Alcohol  Malic.acid   Ash   Acl  ...  Color.int   Hue    OD  Proline
0      14.23        1.71  2.43  15.6  ...       5.64  1.04  3.92     1065
1      13.20        1.78  2.14  11.2  ...       4.38  1.05  3.40     1050
2      13.16        2.36  2.67  18.6  ...       5.68  1.03  3.17     1185
3      14.37        1.95  2.50  16.8  ...       7.80  0.86  3.45     1480
4      13.24        2.59  2.87  21.0  ...       4.32  1.04  2.93      735
..       ...         ...   ...   ...  ...        ...   ...   ...      ...
173    13.71        5.65  2.45  20.5  ...       7.70  0.64  1.74      740
174    13.40        3.91  2.48  23.0  ...       7.30  0.70  1.56      750
175    13.27        4.28  2.26  20.0  ...      10.20  0.59  1.56      835
176    13.17        2.59  2.37  20.0  ...       9.30  0.60  1.62      840
177    14.13        4.10  2.74  24.5  ...       9.20  0.61  1.60      560

[178 rows x 13 columns]


In [ ]:
y=data['Wine']
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [ ]:
clf=RandomForestClassifier(n_estimators=10)
model=clf.fit(X_train,y_train)
predict=clf.predict(X_test)
print(predict)


[1 2 2 1 3 1 1 1 2 2 1 2 1 3 2 3 1 1 2 3 2 2 1 3 2 3 3 2 2 2 1 1 3 2 3 2]


In [ ]:
output=pd.DataFrame(predict,y_test)
print(output)

      0
Wine   
1     1
2     2
2     2
1     1
3     3
1     1
1     1
1     1
1     2
2     2
1     1
2     2
1     1
3     3
2     2
3     3
1     1
1     1
2     2
3     3
2     2
2     2
1     1
3     3
2     2
3     3
3     3
2     2
2     2
2     2
1     1
1     1
3     3
2     2
3     3
2     2


In [ ]:
from sklearn import metrics
print("Accuracy of the model :{}".format(metrics.accuracy_score(y_test,predict)))

Accuracy of the model :0.9722222222222222


Using Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)
predict=classifier.predict(X_test)
print(predict)

[1 2 2 1 3 1 1 1 2 2 1 2 1 3 2 3 1 1 2 3 2 2 1 3 2 3 3 2 2 2 1 1 3 2 3 2]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
output=pd.DataFrame(predict,y_test)
print(output)

      0
Wine   
1     1
2     2
2     2
1     1
3     3
1     1
1     1
1     1
1     2
2     2
1     1
2     2
1     1
3     3
2     2
3     3
1     1
1     1
2     2
3     3
2     2
2     2
1     1
3     3
2     2
3     3
3     3
2     2
2     2
2     2
1     1
1     1
3     3
2     2
3     3
2     2


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,predict)
print(cm)

[[12  1  0]
 [ 0 14  0]
 [ 0  0  9]]


In [ ]:
from sklearn.metrics import accuracy_score

score =accuracy_score(y_test,predict)
print("Accuracy of the model :{}".format(score))

Accuracy of the model :0.9722222222222222


In [ ]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,predict)
print('mse is ',mse)

mse is  0.027777777777777776
